name: Create Hot Fix

on:
  workflow_dispatch:

permissions:
  contents: write
  packages: write
  pull-requests: write

jobs:
  release:
    if: github.ref != 'refs/heads/main'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Ensure changeset file exists
        run: compgen -G ".changeset/*-*-*.md"

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version-file: .nvmrc
          registry-url: "https://registry.npmjs.org/"

      - name: Install dependencies
        run: npm ci --ignore-scripts

      - name: Set user
        run: git config user.name github-actions[bot] && git config user.email github-actions[bot]@users.noreply.github.com

      - name: Create Release Pull Request
        uses: changesets/action@v1
        with:
          commitMode: 'github-api'
          publish: npm run github:release
          commit: 'Create new hotfix config version'
          title: 'Create new hotfix config version'
